### ISSUE TITLE
Installation fail Ubuntu 16.10

### ISSUE THREAD

**Issue by DaniloZZZ** [jerryd/gtk-fortran#107]
Hello! gfortran version 6.2.0 Installation with `sudo make install ` fails with following output :
 `CMakeFiles/mandelbrot_pixbuf.dir/mandelbrot_pixbuf.f90.o: In function 'MAIN__':
/home/danil/gtk-fortran/examples/mandelbrot_pixbuf.f90:134: undefined reference to 'sleep_'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/mandelbrot_pixbuf.dir/build.make:104: recipe for target 'examples/mandelbrot_pixbuf' failed
make[2]: *** [examples/mandelbrot_pixbuf] Error 1
CMakeFiles/Makefile2:635: recipe for target 'examples/CMakeFiles/mandelbrot_pixbuf.dir/all' failed
make[1]: *** [examples/CMakeFiles/mandelbrot_pixbuf.dir/all] Error 2
Makefile:160: recipe for target 'all' failed`
What can i do to resilve the issue?

**Comment by vmagnin** [comment]
Hello,
this is strange. I have no problem with this file using 6.2.0 under Kubuntu 16.10. The sleep() function is a GNU extension present in gfortran:
https://gcc.gnu.org/onlinedocs/gfortran/SLEEP.html

A simple workaround is to use the -i option to ignore building problems:
sudo make -i install
You can also edit mandelbrot_pixbuf.f90 and comment the line 134. It is just used for the pause button and is not essential.

But it would be better to understand the problem. The gfortran sleep() function probably use the sleep() function in the libc:
http://www.delorie.com/gnu/docs/glibc/libc_445.html
Linking problems are generally due to a dev file not installed:
**can you verify that the _libc6-dev_ package is installed in your system ?**
