### ISSUE TITLE
git clone fails with "could not read from remote repository"

### ISSUE THREAD

**Issue by DThiebaud** [jerryd/gtk-fortran#121]
$ sudo git clone git@github.com:jerryd/gtkfortran.git
Cloning into 'gtkfortran'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by vmagnin** [comment]
Dear DThiebaud,

First, be sure you have not forgotten the hyphen (gtk-fortran and not gtkfortran):
`$ git clone git@github.com:jerryd/gtk-fortran.git`

You can also try:
`$ git clone https://github.com/jerryd/gtk-fortran.git`
because it is said on https://help.github.com/articles/which-remote-url-should-i-use/ that with the first method (ssh), _"you must generate an SSH keypair on your computer and add the public key to your GitHub account."_ Which is not the case with https:// URLs.

**Comment by DThiebaud** [comment]
The second worked ok.
