### ISSUE TITLE
Missing information in Documentation

### ISSUE THREAD

**Issue by johnsamuelwrites** [jerryd/gtk-fortran#126]
## Unit and functional tests
The documentation does not describe how to run the tests. There is a folder called test with the perl file run_all.pl. But the [main wiki page](https://github.com/jerryd/gtk-fortran/wiki) does not talk about these tests. Also, if perl environment is required, this must also be added in Dependencies section and also in sections related to the different platforms.

## Add links
Under the Download section, it is mentioned
 
> To download all the project files, you can simply clone the repository using git (see git-basics).

Add a link to git-basics.

One suggestion for the Linux section, use apt instead of apt-get (section Linux)

For details on the review process, refer: openjournals/joss-reviews#1014

**Comment by vmagnin** [comment]
Dear John Samuel,

I have added a section in the wiki about testing gtk-fortran:
https://github.com/jerryd/gtk-fortran/wiki#testing-gkt-fortran
Let me know if you find these explications still confused. Perhaps the test.sh script should be moved to the test directory...

Note that there is some perl script because some developers in the project use them, but the users do not need them.

I have added a link in the wiki text toward the "git-basics" page.

I have replaced "apt-get' by "apt" in the wiki.

**Comment by johnsamuelwrites** [comment]
Concerning running the test results, I ran the following command
> ./run_all.pl ../build/examples

But I get the following message. 
> bash: ./run_all.pl: Permission denied

Do I need any special permissions to run test cases)? Also please add the following lines under the testing section
$ cd test
$  ./run_all.pl ../build/examples

**Comment by johnsamuelwrites** [comment]
This is working. Now closing the ticket.
