### ISSUE TITLE
Problem installing gtk-fortran on kubuntu 14.04

### ISSUE THREAD

**Issue by normcler** [jerryd/gtk-fortran#92]
Hello,
I am attempting to install gtk-fortran on my kubuntu laptop. I am using ver. 14.04 LTS.
I wish to use gtk3, so I cloned the gtk3 branch. All the files and subdirectories are located in directory
~/Dropbox/home-lima/norm/fortran/gtk3. Unfortunately, I am not at all familiar with CMake. I set my working directory to this directory and run cmake .. I see the following message:

norm@lima:~/Dropbox/home-lima/norm/fortran/gtk3$ /usr/local/cmake/cmake-3.5.2-Linux-x86_64/bin/cmake ..
CMake Error: The source directory "/home/norm/Dropbox/home-lima/norm/fortran" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

If I move up one in the directory tree, i.e., I enter cd .., moving to subdirectory fortran, and rerun cmake, I get a similar message saying that CMakeLists.txt cannot be found in subdirectory norm.

There is a file CMakeLists.txt, but it's located in the gtk3 subdirectory.

Any suggestions?

thank for your assistance. I really want to get gtk-fortran running (and I'll test it using the stringent NAG Fortran compiler when I do)

Norm Clerman

**Comment by vmagnin** [comment]
Hi Norm,
welcome to gtk-fortran,
first I think it is compulsory to keep the original name of the directory:
`~/Dropbox/home-lima/norm/fortran/gtk-fortran/`
Then, the instructions are in the INSTALL file: from the gtk-fortran/ directory, type:
```
    mkdir build
    cd build
    cmake ..
    make
    sudo make install
```

If you use gcc5, please see the issue https://github.com/jerryd/gtk-fortran/issues/89 for "A workaround to build gtk-fortran with gcc 5", because there is a bug in gcc5 when compiling two examples of the project.
If you test compilation with NAG, thank you to post your experience.

Vincent

**Comment by normcler** [comment]
Hello Vincent,
Some progress made:
I get 50% through the make phase and I see the following:

...
Scanning dependencies of target notebooks
[ 50%] Building Fortran object examples/CMakeFiles/notebooks.dir/notebooks.f90.o
[ 50%] Linking Fortran executable notebooks
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so: undefined reference to `g_type_class_adjust_private_offset'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/notebooks] Error 1
make[1]: *** [examples/CMakeFiles/notebooks.dir/all] Error 2
make: *** [all] Error 2

I'm missing something. Any suggestions?

Thanks,
Norm

**Comment by vmagnin** [comment]
Hello Norm,
I found that in /usr/include/glib-2.0/gobject/gtype.h:
```
GLIB_AVAILABLE_IN_2_38
void     g_type_class_adjust_private_offset (gpointer                g_class,
```
Which version of glib is in your system ? You need 2.38 or higher for this gtk-fortran branch.

There are several solutions:
- upgrading to Kubuntu 16.04 LTS,
- loading the gtk3-old branch (compiled with gtk+ 3.2 and glib 2.30) from github,
- trying to regenerate the gtk-fortran files with cfwrapper.py for your system,
- trying to comment the lines concerning notebooks.f90 in the CMakeLists.txt file,
- ...

I will try to help you.
Vincent

**Comment by normcler** [comment]
Vincent,

Thanks for again replying so promptly. Good excuse for me to upgrade to
version 16.04 LTS.

By the way, the Windows version of the NAG compiler comes with GTK+. I'm
not sure if it's using gtk-fortran. Here's the link (on Windows the NAG
compiler is called Fortran Builder; it's an IDE).

http://nag.com/nagware/NP/fortranbuilder.asp

You may already know that the NAG compiler is the best for finding bugs in
your source code as shown in the table in this link:

http://www.fortran.uk/fortran-compiler-comparisons-2015/intellinux-fortran-compiler-diagnostic-capabilities/

It doesn't, by far, create the fastest running code, but I always run my
code through it to find bugs.

Thanks again,





*Norm**Norman S. Clerman*
norm.clerman@gmail.com

**Comment by vmagnin** [comment]
Norman,
master and gtk3 branches are OK with Ubuntu 16.04, but a little workaround (just four lines to comment) is necessary because of a bug in gcc5 which prevents to build two of the examples:
issue https://github.com/jerryd/gtk-fortran/issues/89

Note that these branches were created with previous versions of gtk+ and glib. I am working on the python script cfwrapper.py to adapt it to the last versions available in 16.04:
issue https://github.com/jerryd/gtk-fortran/issues/93
Each version of the libraries come with new functions but also often new little problems for my python script. Parsing 700 .h files is not easy...

Thanks for the infos about NAG Fortran. I will have a look. I do not think it uses gtk-fortran because of the GPL3 license:
issue https://github.com/jerryd/gtk-fortran/issues/24
but perhaps gtk-fortran showed the way...
I have been using Compaq Visual Fortran for many years, under Windows at first then with Wine under Linux. But I now use mainly gfortran under Linux. I have also bought the Intel Fortran for Linux, but my code is faster with gfortran (the 4.8.5 version is the fastest of all the versions available under Ubuntu). And gfortran yields more warnings about the code.

Vincent
P.s. _Modern Fortran_ is a great and useful book ! ;-)

**Comment by normcler** [comment]
Vincent,

First, thank you for your complement about *Modern Fortran*; I'm glad you
like it. I have accumulated a healthy set of errata that I just haven't had
time to post. I have more time now, so perhaps I will. Cambridge Univ.
Press doesn't put errata directly on their site, but they will provide a
link to a site containing it. I do not have experience with this. What's
the best spot to put errata, on? GitHub?

Second, I won't be able to upgrade my OS until next week at the earliest.
I've noted issues number 89 and 93 for when I again try to build
gtk-fortran.

I'm surprised gfortran runs faster for you than Intel. I haven't used
gfortran enough to really make the comparison myself, but I've found Intel
to be extremely fast. If you look at the Polyhedron compiler comparisons,
the data back this up. Intel is also making good headway in having a
totally compliant Fortran 2003 compiler. The new version, for example, has
sub-modules. At least until recently, the only compilers that had those was
IBM and Cray.

Thanks again.





*Norm**Norman S. Clerman*
norm.clerman@gmail.com

**Comment by vmagnin** [comment]
I found an example of errata here: http://www.fortran.com/fortran-2003-handbook-errata/
or here: http://www.cs.utsa.edu/faculty/atc/CS1073files/Errata_Sheet_for_Fortran_95_2003_for_Scientists_and_Engineers_3e.pdf
but why not on your GitHub ? We can expect it to have a sufficient perennity. You could put a simple ascii file or create a wiki.

If you have problems during your upgrade, you can contact me. I have upgraded 12 PC toward Kubuntu 16.04, and among them 5 from the 14.04 LTS. The 16.04 is now stable and I am very satisfied with it. Upgrading from 14.04 LTS, I first obtained a message telling me that the upgrade was impossible because of some packages (but which ?) but I found somewhere the solution:
```
$ cat /var/log/dist-upgrade/main.log | grep Obsolete
2016-04-22 16:17:21,822 DEBUG Obsolete: libgd2-xpm linux-image-3.5.0-31-generic linux-image-extra-3.5.0-31-generic
$ sudo apt-get remove libgd2-xpm linux-image-3.5.0-31-generic linux-image-extra-3.5.0-31-generic

```
Concerning Intel Fortran, perhaps I have not found the best compilation options... But the best results I obtained with my ray tracing code were:

- /opt/intel/bin/ifort -fast -march=corei7 -mtune=corei7 : 18.6 s
- gfortran-4.8 -O3 -march=native -mtune=native : 17.6 s

Concerning gfortran, my experience is that the more recent version (5.3.1) are better for diagnostics, but tend to give a slower code than older versions. The 4.8.5 is faster than the 4.9.3 and 5.3.1 available in Kubuntu 16.04. In fact the 4.8 branch is now maintained since 2013 and has been debugged extensively. The 5 branch seems to have introduced regressions in terms of speed. Things evolve and the 5.3.1 is faster than the 5.2.1 but I hope future versions will improve speed. Of course, I speak of differences less than 10% but we know what it means with far longer computations.

**Comment by vmagnin** [comment]
Hi Norman,
I have updated the gtk-fortran/src/test.sh script in the master and gtk3 branches. You can use it to compile the gtk-fortran files and examples and run them. It does not install the gtk-fortran library on your system, but it is a more basic way of using gtk-fortran than the CMake way.

If you know which gtk-fortran files are needed, you can also compile and run each example as follow:
```
$ gfortran gtk.f90 ../examples/julia_pixbuf.f90 `pkg-config --cflags --libs gtk+-3.0`
$ ./a.out
```

V.

**Comment by vmagnin** [comment]
See the new workaround to issue https://github.com/jerryd/gtk-fortran/issues/89
Just type `make -i` to ignore errors !

**Comment by vmagnin** [comment]
I close that issue because it is an old post, but don't hesitate to reopen if the problem persists.
